### ISSUE TITLE
Metrics-sampler stop send weblogic metrics after connection fail.

### ISSUE THREAD

**Issue by IldarMinaev** [dimovelev/metrics-sampler#8]
I use metrics-sampler to garbage metrics from weblogic server via jmx input and push it to graphite server.
If weblogic server not available (by network issue or by restarting weblogic node) I see the error in metrics-sampler log about connection issue, and after the recover of connection to weblogic node, metrics-sampler does not send metrics from failed node to graphite. Only restartimg of metrics-sampler helps to work fine.
Same problem if I have restart graphite server - no one metric pushed to graphit until restart of metrics-sampler, and cpu usage of metrics-sampler process increased.

**Comment by dimovelev** [comment]
The probable cause for the issue is that when you restart the weblogic server it takes a while for it to completely load. If metrics-sampler samples the metrics while the server is still starting up (and not all JMX beans have been published), it will only match a few (or none at all) metrics. I have added a feature a while back that resets the number of matched metrics after a reconnect. Every time we sample we compare the number of matched metrics with the previous count and keep on matching every time until the number of matched metrics remains the same.

Check out the two sampler configuration attributes - org.metricssampler.extensions.base.DefaultSamplerConfig#getInitialResetTimeout and getRegularResetTimeout. The latter one makes sure that you reconnect on a regular base just in case.

If that does not solve your problem (although it has been a while since you opened that) let me know - it might be a network related issue - in this case you might need to configure tcp keep-alive and/or socket timeouts.
